services:
  web:
    container_name: gaming_web
    build:
      context: .
    command: gunicorn -w 2 -b 0.0.0.0:5050 'src.app.main:create_app()'
    restart: unless-stopped
    networks:
      - proxy-tier
    environment:
      - PYTHONPATH=/app/src
      - FLASK_ENV=production
      - FLASK_APP=src/run.py
      # Point these to your new Database LXC
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

networks:
  proxy-tier:
    external: true
