"""rename console table to platform and update FKs

Revision ID: 648aa0451afa
Revises: 72097d55382a
Create Date: 2025-12-15 20:01:41.251894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '648aa0451afa'
down_revision = '72097d55382a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Create the new platform table
    op.create_table('platform',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('manufacturer', sa.String(length=100), nullable=True),
        sa.Column('release_year', sa.Integer(), nullable=True),
        sa.Column('generation', sa.String(length=50), nullable=True),
        sa.Column('description', sa.String(length=250), nullable=True),
        sa.Column('cost', sa.Float(), nullable=True),
        sa.Column('quantity', sa.Integer(), nullable=True),
        sa.Column('purchased_from', sa.String(length=100), nullable=True),
        sa.Column('ownership_id', sa.Integer(), nullable=True),
        sa.Column('notes', sa.String(length=200), nullable=True),
        sa.ForeignKeyConstraint(['ownership_id'], ['category.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )

    # 2. Drop FKs and columns referencing console
    op.drop_constraint('game_console_id_fkey', 'game', type_='foreignkey')
    op.drop_constraint('peripheral_console_id_fkey', 'peripheral', type_='foreignkey')
    op.drop_column('game', 'console_id')
    op.drop_column('peripheral', 'console_id')

    # 3. Drop the old console table
    op.drop_table('console')

    # 4. Add platform_id columns and FKs
    op.add_column('game', sa.Column('platform_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'game', 'platform', ['platform_id'], ['id'])
    op.add_column('peripheral', sa.Column('platform_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'peripheral', 'platform', ['platform_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peripheral', sa.Column('console_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('peripheral_platform_id_fkey', 'peripheral', type_='foreignkey')
    op.create_foreign_key(op.f('peripheral_console_id_fkey'), 'peripheral', 'console', ['console_id'], ['id'])
    op.drop_column('peripheral', 'platform_id')
    op.add_column('game', sa.Column('console_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('game_platform_id_fkey', 'game', type_='foreignkey')
    op.create_foreign_key(op.f('game_console_id_fkey'), 'game', 'console', ['console_id'], ['id'])
    op.drop_column('game', 'platform_id')
    op.create_table('console',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('manufacturer', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('release_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('generation', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('purchased_from', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ownership_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ownership_id'], ['category.id'], name=op.f('console_ownership_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('console_pkey')),
    sa.UniqueConstraint('name', name=op.f('console_name_key'))
    )
    op.drop_table('platform')
    # ### end Alembic commands ###
