"""refactor to use console_id for Game and Peripheral

Revision ID: 72097d55382a
Revises: dc6447adc562
Create Date: 2025-12-15 17:47:15.571099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72097d55382a'
down_revision = 'dc6447adc562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('console_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('game_platform_id_fkey'), 'game', type_='foreignkey')
    op.create_foreign_key(None, 'game', 'console', ['console_id'], ['id'])
    op.drop_column('game', 'platform_id')
    op.add_column('peripheral', sa.Column('console_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('peripheral_platform_id_fkey'), 'peripheral', type_='foreignkey')
    op.create_foreign_key(None, 'peripheral', 'console', ['console_id'], ['id'])
    op.drop_column('peripheral', 'platform_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peripheral', sa.Column('platform_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'peripheral', type_='foreignkey')
    op.create_foreign_key(op.f('peripheral_platform_id_fkey'), 'peripheral', 'category', ['platform_id'], ['id'])
    op.drop_column('peripheral', 'console_id')
    op.add_column('game', sa.Column('platform_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.create_foreign_key(op.f('game_platform_id_fkey'), 'game', 'category', ['platform_id'], ['id'])
    op.drop_column('game', 'console_id')
    # ### end Alembic commands ###
