"""add grade column to game

Revision ID: a144cdae5a0e
Revises: 648aa0451afa
Create Date: 2025-12-15 20:48:23.353175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a144cdae5a0e'
down_revision = '648aa0451afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('grade', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'grade')
    # ### end Alembic commands ###
