"""add_missing_peripheral_fields

Revision ID: dc6447adc562
Revises: eab659f8b723
Create Date: 2025-12-15 17:42:42.885924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc6447adc562'
down_revision = 'eab659f8b723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peripheral', sa.Column('cost', sa.Float(), nullable=True))
    op.add_column('peripheral', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('peripheral', sa.Column('purchased_from', sa.String(length=100), nullable=True))
    op.add_column('peripheral', sa.Column('ownership_id', sa.Integer(), nullable=True))
    op.add_column('peripheral', sa.Column('notes', sa.String(length=200), nullable=True))
    op.create_foreign_key(None, 'peripheral', 'category', ['ownership_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'peripheral', type_='foreignkey')
    op.drop_column('peripheral', 'notes')
    op.drop_column('peripheral', 'ownership_id')
    op.drop_column('peripheral', 'purchased_from')
    op.drop_column('peripheral', 'quantity')
    op.drop_column('peripheral', 'cost')
    # ### end Alembic commands ###
