"""add console table

Revision ID: eab659f8b723
Revises: c9336234feb1
Create Date: 2025-12-15 17:23:46.449590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eab659f8b723'
down_revision = 'c9336234feb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('console',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('generation', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('purchased_from', sa.String(length=100), nullable=True),
    sa.Column('ownership_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['ownership_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.alter_column('game', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('game', 'quantity')
    op.drop_column('game', 'peripheral_type')
    op.drop_column('game', 'purchased_from')
    op.drop_column('game', 'platform_type')
    op.drop_constraint(op.f('peripheral_ownership_id_fkey'), 'peripheral', type_='foreignkey')
    op.drop_column('peripheral', 'notes')
    op.drop_column('peripheral', 'cost')
    op.drop_column('peripheral', 'purchased_from')
    op.drop_column('peripheral', 'ownership_id')
    op.drop_column('peripheral', 'quantity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peripheral', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('peripheral', sa.Column('ownership_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('peripheral', sa.Column('purchased_from', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('peripheral', sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('peripheral', sa.Column('notes', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('peripheral_ownership_id_fkey'), 'peripheral', 'category', ['ownership_id'], ['id'])
    op.add_column('game', sa.Column('platform_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('game', sa.Column('purchased_from', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('game', sa.Column('peripheral_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('game', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('game', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_table('console')
    # ### end Alembic commands ###
